name: Build and Publish

on:
  workflow_call:
    inputs:
      app_version:
        type: string
        required: true
      app_release_name:
        type: string
        required: true
      gcp_artifact_registry:
        type: string
        required: true
      gcp_project_id:
        type: string
        required: true
      gcp_service_account:
        type: string
    secrets:
      LIVERPOOL_GOOGLE_APPLICATION_CREDENTIALS:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: slug
        run: |
          echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "img_version=$(grep appVersion "./gradle.properties" | cut -d '=' -f2)" >> $GITHUB_OUTPUT

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ inputs.project_id }}
          service_account: ${{ inputs.service_account }}
          credentials_json: ${{ secrets.LIVERPOOL_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.gcp_artifact_registry }}
          username: _json_key
          password: ${{ secrets.LIVERPOOL_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Build, tag and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_URL: ${{ inputs.gcp_artifact_registry }}/${{ inputs.app_release_name }}
        with:
          push: true
          tags: ${{ env.IMAGE_URL }}:latest,${{ env.IMAGE_URL }}:${{ steps.slug.outputs.sha7 }},${{ env.IMAGE_URL }}:${{ inputs.app_version }}
          cache-from: type=registry,ref=${{ env.IMAGE_URL }}:latest
          cache-to: type=inline
          build-args: |
            docker_image=${{ inputs.app_release_name }}:${{ steps.slug.outputs.sha7 }}
            IMAGE_VERSION=${{ steps.slug.outputs.img_version }}
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
