name: Publish NPM

on:
  workflow_call:
    inputs:
      branch:
        default: main
        required: false
        type: string
        description: Branch to release from.

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

env:
  NODE_VERSION: '20.x'

jobs:
  # versioning:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  release:
    # needs:
    #   - versioning

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure GCP Credentials
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ vars.JSON_CREDENTIALS }}

      # Update the .npmrc file with the token autorization
      - run: npx google-artifactregistry-auth

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: feature/javascript-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: npm publish
