name: Publish NPM

on:
  workflow_call:
    inputs:
      branch:
        default: main
        type: string
        required: false
        description: The branch to release from.
      scope:
        type: string
        required: true
        description: The scope of the NPM package.
      location:
        type: string
        required: true
        description: The location of the Artifact Registry repository.
      project_id:
        type: string
        required: true
        description: The ID of the Google Cloud project.
      repository_id:
        type: string
        required: true
        description: The ID of the Artifact Registry repository.


permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

env:
  NODE_VERSION: '20.x'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure GCP Credentials
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ vars.JSON_CREDENTIALS }}

      - name: Configure NPMRC file
        run: |
          echo "${{ inputs.scope }}:registry=https://${{ inputs.location }}-npm.pkg.dev/${{ inputs.project_id }}/${{ inputs.repository_id }}/" >> .npmrc
          echo "//${{ inputs.location }}-npm.pkg.dev/${{ inputs.project_id }}/${{ inputs.repository_id }}/:always-auth=true" >> .npmrc

      # Update the .npmrc file with the token autorization
      - run: npx google-artifactregistry-auth

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
