name: Publish NPM

on:
  push: {}
  # workflow_call:
  #   inputs:
  #     checkmarx_break_build:
  #       type: boolean
  #       default: true
  #   secrets:
  #     codacy_project_token:
  #       required: true
  #     _checkmarx_url:
  #       required: true
  #     _checkmarx_username:
  #       required: true
  #     _checkmarx_password:
  #       required: true
  #     _checkmarx_client_secret:
  #       required: true
  #     _sca_tenant:
  #       required: true
  #     _sca_username:
  #       required: true
  #     _sca_password:
  #       required: true

permissions:
  contents: write

env:
  NODE_VERSION: '20.x'

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs:
      - versioning

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure GCP Credentials
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ vars.JSON_CREDENTIALS }}

      # Update the .npmrc file with the token autorization
      - run: npx google-artifactregistry-auth

      - name: Install dependencies
        run: npm install

      - run: npm publish
