name: Publish

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app_image_version:
        type: string
        required: true
      app_image_url:
        type: string
        default: kata-demo-artifact-repo
        required: true
      app_release_name:
        type: string
        required: true
      k8s_namespace:
        type: string
        required: true
      gcp_project_id:
        type: string
        required: true
      gcp_service_account:
        type: string
        required: true
      gcp_cluster_name:
        type: string
        required: true
      gcp_location:
        type: string
        default: 'us-east1'
        required: true
      helm_repository:
        type: string
        default: 
      helm_chart_version:
        type: string
        default: 1.0.0
        required: true
      helm_wait:
        type: string
        default: 'true'
      helm_atomic:
        type: string
        default: 'false'
      helm_values:
        type: string
        description: "Path to helm values yaml file"
        required: false
    secrets:
      LIVERPOOL_GOOGLE_APPLICATION_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ inputs.gcp_project_id }}
          service_account: ${{ inputs.gcp_service_account }}
          credentials_json: ${{ secrets.LIVERPOOL_GOOGLE_APPLICATION_CREDENTIALS }}

      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ inputs.gcp_cluster_name }}
          location: ${{ inputs.gcp_location }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Log in to Artifact Repository
        run: |
          gcloud auth application-default print-access-token | helm registry login \
            -u oauth2accesstoken \
            --password-stdin https://${{ inputs.helm_repository }}

      - name: Deploy
        shell: bash
        env:
          wait_enabled: ${{ inputs.helm_wait }}
          atomic_enabled: ${{ inputs.helm_atomic }}
          helm_values: ${{ inputs.helm_values }}
        run: |
          cmd="helm upgrade ${{ inputs.app_release_name }} oci://${{ inputs.helm_repository }}"
          cmd+=" --version ${{ inputs.helm_chart_version }}"
          cmd+=" --namespace ${{ inputs.k8s_namespace }}"
          cmd+=" --set image.repository=${{ inputs.app_image_url }}"
          cmd+=" --set-string image.tag=${{ inputs.app_image_version }}"

          if [[ -n $helm_values ]]; then
            cmd+=" --values $helm_values"
          fi
          
          if [[ $wait_enabled == 'true' ]]; then
            cmd+=" --wait"
          fi
          
          if [[ $atomic_enabled == 'true' ]]; then
            cmd+=" --atomic"
          fi
          
          cmd+=" --install"
            
          echo $cmd
          eval $cmd

          # Check if it was successful
          if [ $? -eq 0 ]; then
            echo "The command was successful: $cmd"
          else
            echo "The command failed: $cmd"
          fi
