name: demo release

on: 
  push:
    paths: app

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  release:
    uses: JonDotsoy/sample-workflow/.github/workflows/npm-release.yml@demo-v4
    with:
      branch: feature/javascript-release
      scope: "@inkybrowser-npm"
      location: us-east1
      project_id: jondotsoy
      repository_id: inkybrowser-npm
