name: demo release

on: push

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  release:
    uses: JonDotsoy/sample-workflow/.github/workflows/npm-release.yml@vdemo
    with:
      branch: feature/javascript-release
