name: demo release

on: push

permissions:
  contents: write

jobs:
  setup_envs:
    runs-on: ubuntu-latest
    outputs:
      environment_json: ${{ steps.parse_environment_json.outputs.environment_json }}
    env:
      environment: |
        - Plan-Development
        - Plan-QA
      #  - Plan-Production
    steps:
      - run: echo "$environment" | yq '. | @json | @sh | "environment_json=" + .' -r > "$GITHUB_OUTPUT"
        id: parse_environment_json

  by_matrix:
    runs-on: ubuntu-latest
    needs:
      - setup_envs
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup_envs.outputs.environment_json) }}

    steps:
      - run: echo ${{ matrix.environment }}

  # matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     rand: ${{ steps.rand.outputs.rand }}
  #   strategy:
  #     matrix:
  #       n:
  #         - 1
  #         - 2
  #   steps:
  #     - run: echo "rand=${{ matrix.n }}" > "$GITHUB_OUTPUT"
  #       id: rand
  # release:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - matrix
  #   steps:
  #     - run: echo ${{ toJson(needs) }}
