name: demo release

on: push

permissions:
  contents: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      rand: ${{ steps.rand.outputs.rand }}
    strategy:
      matrix:
        n:
          - 1
          - 2
    steps:
      - run: echo "rand=$RANDOM" > "$GITHUB_OUTPUT"
        id: rand
  release:
    runs-on: ubuntu-latest
    needs: 
      - matrix
    steps:
      - run: echo ${{ toJson(needs.matrix.outputs) }}
