name: demo release

on: push

permissions:
  contents: write

jobs:
  setup_environment_options:
    runs-on: ubuntu-latest
    outputs:
      environment_options_json: ${{ steps.parse_environment_options_json.outputs.environment_options_json }}
    env:
      environment_options: |
        - environment: Plan-Development
          source_path: k8s-admin
        - environment: Plan-QA
          source_path: k8s-admin
      #  - environment: Plan-Production
      #    source_path: k8s-admin
    steps:
      - run: |
          echo "$environment_options" | yq '. | @json | "environment_options_json=" + .' -r > "$GITHUB_OUTPUT"
          echo $RANDOM > random.out
        id: parse_environment_options_json
      - uses: actions/upload-artifact@v4
        with:
          name: art_${{ toJson(steps.parse_environment_options_json.outputs.parse_environment_options_json).source_path }}_${{ toJson(steps.parse_environment_options_json.outputs.environment_options_json).environment }}
          path: |
            random.out

  by_matrix:
    runs-on: ubuntu-latest
    needs:
      - setup_environment_options
    strategy:
      matrix:
        environment_options: ${{ fromJson(needs.setup_environment_options.outputs.environment_options_json) }}
    steps:
      - run: |
          echo environment=$environment
          echo source_path=$source_path
        env:
          environment: ${{ matrix.environment_options.environment }}
          source_path: ${{ matrix.environment_options.source_path }}
      - uses: actions/download-artifact@v4
      - run: ls -lah

  # matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     rand: ${{ steps.rand.outputs.rand }}
  #   strategy:
  #     matrix:
  #       n:
  #         - 1
  #         - 2
  #   steps:
  #     - run: echo "rand=${{ matrix.n }}" > "$GITHUB_OUTPUT"
  #       id: rand
  # release:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - matrix
  #   steps:
  #     - run: echo ${{ toJson(needs) }}
